service: content-based-filtering

useDotenv: true
plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  stage: ${env:ENVIRONMENT}
  runtime: nodejs14.x
  region: us-east-1
  vpc:
    securityGroupIds:
      - ${file(${env:ECS_CONFIG}/bin/vars.yml):us-east-1.webapp_elb_sg}
    subnetIds: ${file(${env:ECS_CONFIG}/bin/vars.yml):us-east-1.prod_apps_1_all}
  stackTags:
    Name: ${env:PROJECT_NAME}-${self:custom.environmentMap.${env:ENVIRONMENT}}
    owner: apps@cru.org
    application: ${env:PROJECT_NAME}
    env: ${self:custom.environmentMap.${env:ENVIRONMENT}}
    managed_by: serverless-framework
    function: lambda

package:
  individually: true
  exclude:
    - .serverless/**
    - .git/**
    - test/**
    - '**/*.test.js'
    - .deployment/**

custom:
  environmentMap:
    production: prod
    staging: stage
    development: dev
    lab: lab

functions:
  handler:
    handler: src/index.handler
    events:
      # Run every 30 minutes.
      - schedule: cron(0/30 * * * ? *)
